name: Python Checks

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9","3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Conda environment 
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: anaconda-client-env
          environment-file: conda-environment.yml
          auto-activate-base: false
      - name: Install dependencies
        run: |
          conda env update --file conda-environment.yml --name base
      - name: Check Conda info
        run: |
          conda info
          conda list
      - name: Test with pytest
        run: |
          pytest tests/test_actions.py -v
      - name: Lint with ruff
        run: |
          # stop the build if there are Python syntax errors or undefined names
          ruff --format=github --select=E9,F4,F6,F7,F8,N8 --ignore=F405 --target-version=py37 .
